apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: shouts.agh.edu.pl
spec:
  group: agh.edu.pl
  version: v1alpha1
  names:
    kind: Shout
    plural: shouts
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            text:
              type: string
            count:
              type: integer
              minimum: 1
              maximum: 10
